spring:
  application:
    name: hospital-b

  datasource:
    url: jdbc:postgresql://postgres-b:5432/patients_data
    username: postgres
    password: Kshitij@7
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        lob:
          non_contextual_creation: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: hospitalB-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: 91d74b002@smtp-brevo.com
    password: O1sGcZxvnbhU6yLw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

topic:
  patient-data: patient-data-request

security:
  aes-key: 1234567890123456

hospital:
  kafka:
    topic: ireland-hospital-response

server:
  port: 8081

spring.kafka.consumer.group-id: hospitalB-group
