spring:
  application:
    name: india-hospital

  datasource:
    url: jdbc:postgresql://postgres-a:5432/healthcare
    username: postgres
    password: Kshitij@7
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: hospitalA-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: manual
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

topic:
  patient-data: patient-data-request

security:
  aes-key: 1234567890123456

management:
  tracing:
    enabled: false
  otlp:
    metrics:
      export:
        enabled: false
    tracing:
      endpoint: none

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    io.opentelemetry.exporter.internal.grpc.GrpcExporter: OFF
